library(ggdendro)
library(ggplot2)
library(reshape)
library(RColorBrewer)

mydplot <- function(ddata, row=!col, col=!row, labels=col, label.expand=c(0.1,0)) {
  ## plot a dendrogram
yrange <- range(ddata$segments$y)
yd <- yrange[2] - yrange[1]
nc <- max(nchar(as.character(ddata$labels$label)))
tangle <- if(row) { 0 } else { 90 }
tshow <- col
p <- ggplot() +
  geom_segment(data=segment(ddata), aes(x=x, y=y, xend=xend, yend=yend)) +
    scale_x_continuous(expand=c(0,0)) +
      labs(x = NULL, y = NULL) 
if(labels) # only show column labels
  p <- p + geom_text(data=ddata$labels, aes(x=x, y=y, label=label), size=2,
                     angle=tangle, vjust=1, hjust=1) +
                       scale_y_continuous(expand=label.expand)
if(row)
  p <- p + coord_flip() 
return(p + theme_dendro())
}

g_legend<-function(a.gplot){
## from
  ## http://stackoverflow.com/questions/11883844/inserting-a-table-under-the-legend-in-a-ggplot2-histogram
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

ggheatmap.show <- function(L, col.width=0.2, row.width=0.2) {
  ## L: a list with 3 named plots: col, row, centre, generated by ggheatmap
  ## col.width: fraction of the device devoted to column dendro 
  ## row.width: fraction of the device devoted to row dendro
  grid.newpage()
  top.layout <- grid.layout(nrow = 2, ncol = 2,
                            widths = unit(c(1-row.width,row.width), "null"),
                            heights = unit(c(col.width,1-row.width), "null"))
  pushViewport(viewport(layout=top.layout))
  print(L$col, vp=viewport(layout.pos.col=1, layout.pos.row=1))
  print(L$row, vp=viewport(layout.pos.col=2, layout.pos.row=2))
  ## print centre without legend
  print(L$centre + 
        scale_x_continuous(expand=c(0,0)) + 
        scale_y_continuous(expand=c(0,0)) +
        opts(axis.line=theme_blank(),
             axis.text.x=theme_blank(),axis.text.y=theme_blank(),
             axis.ticks=theme_blank(),
             axis.title.x=theme_blank(),axis.title.y=theme_blank(),
             legend.position="none",
             panel.background=theme_blank(),
             panel.border=theme_blank(),panel.grid.major=theme_blank(),
             panel.grid.minor=theme_blank(),plot.background=theme_blank()),
        vp=viewport(layout.pos.col=1, layout.pos.row=2))
  ## add legend
  legend <- g_legend(L$centre)
  pushViewport(viewport(layout.pos.col=2, layout.pos.row=1))
  grid.draw(legend)
  upViewport(0)
}

ggheatmap <- function(x,
                      hm.colours=rev(brewer.pal(15,name="RdYlBu"))) {
  ## plot a heatmap
  ## x is an expression matrix
  row.hc <- hclust(dist(x), "ward")
  col.hc <- hclust(dist(t(x)), "ward")
  row.dendro <- dendro_data(as.dendrogram(row.hc),type="rectangle")
  col.dendro <- dendro_data(as.dendrogram(col.hc),type="rectangle")

  ## dendro plots
  col.plot <- mydplot(col.dendro, col=TRUE, labels=TRUE, label.expand=c(0.4,0)) + opts(plot.margin = unit(rep(0, 4), "lines"))
  row.plot <- mydplot(row.dendro, row=TRUE, labels=FALSE) + opts(plot.margin = unit(rep(0, 4), "lines"))

  ## order of the dendros
  col.ord <- match(col.dendro$labels$label, colnames(x))
  row.ord <- match(row.dendro$labels$label, rownames(x))
  xx <- x[row.ord,col.ord]
  dimnames(xx) <- NULL
  xx <- melt(xx)

  centre.plot <- ggplot(xx, aes(X2,X1)) + geom_tile(aes(fill=value), colour="white") +
    scale_fill_gradientn(colours = hm.colours) +
      opts(plot.margin = unit(rep(0, 4), "lines")) +
        labs(x = NULL, y = NULL) + scale_x_continuous(breaks = NULL) +
          scale_y_continuous(breaks = NA)  + scale_x_continuous(expand=c(0,0))  + scale_y_continuous(expand=c(0,0)) 
  
  ret <- list(col=col.plot,row=row.plot,centre=centre.plot)
  invisible(ret)
}
