#+TITLE:     randomFunctions
#+AUTHOR:    Chris Wallace
#+EMAIL:     chris.wallace@cimr.cam.ac.uk
#+DATE:      2013-09-26 Thu
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:(not LOGBOOK) todo:t pri:nil tags:t

#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

R functions for which I want some version control

Note, these are public because there's no point in making them
private, but that doesn't mean they will be useful to you! You are
welcome to give them a go and I always appreciate anyone spotting bugs
in my code.

I have put them in one package not because they are in any way related
to each other, but because I like to have them around without
cluttering up my current environment.

I keep some notes about some of these functions at my
[[http://cwcode.wordpress.com][code blog]].

* Functions

- ggplot-heatmap.R makes heatmaps in ggplot2
- getArgs.R makes parsing commandArgs() easy for use in Rscripts
- abf.R calculates approximate BayesFactors from p values and MAF.
  See Wakefield, J (2009) Bayes factors for genome-wide association
  studies: comparison with p-values.  Genetic Epidemiology 33: 79–86.
